name: gh3
description: "Github Client 3"
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  injectable: ^2.5.0
  get_it: ^8.0.3
  envied: ^1.1.1
  http: ^1.4.0
  shared_preferences: ^2.0.0
  flutter_custom_tabs: ^2.4.0
  flutter_octicons: ^1.52.0
  go_router: ^16.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  injectable_generator: ^2.7.0
  envied_generator: ^1.1.1

flutter:
  uses-material-design: true
