// Mocks generated by Mockito 5.4.6 from annotations
// in gh3/test/screens/user_details/user_details_route_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:gh3/src/screens/user_details/user_details_viewmodel.dart'
    as _i2;
import 'package:gh3/src/screens/user_details/user_details_viewmodel_factory.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserDetailsViewModel_0 extends _i1.SmartFake
    implements _i2.UserDetailsViewModel {
  _FakeUserDetailsViewModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserDetailsViewModelFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDetailsViewModelFactory extends _i1.Mock
    implements _i3.UserDetailsViewModelFactory {
  MockUserDetailsViewModelFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserDetailsViewModel create(String? login) =>
      (super.noSuchMethod(
            Invocation.method(#create, [login]),
            returnValue: _FakeUserDetailsViewModel_0(
              this,
              Invocation.method(#create, [login]),
            ),
          )
          as _i2.UserDetailsViewModel);
}

/// A class which mocks [UserDetailsViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDetailsViewModel extends _i1.Mock
    implements _i2.UserDetailsViewModel {
  MockUserDetailsViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get login =>
      (super.noSuchMethod(
            Invocation.getter(#login),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#login),
            ),
          )
          as String);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get disposed =>
      (super.noSuchMethod(Invocation.getter(#disposed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void onDispose() => super.noSuchMethod(
    Invocation.method(#onDispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );
}
