name: mcp_flutter_automation
description: MCP server for Flutter app automation - launch, logs, screenshots, and inspection
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  vm_service: ^14.0.0
  path: ^1.9.0
  args: ^2.5.0
  logging: ^1.2.0
  web_socket_channel: ^3.0.0
  http: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

executables:
  mcp_flutter_automation: