name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_format_analyze_test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Check code format
        run: dart format --set-exit-if-changed .

      - name: Run Dart analyzer
        run: flutter analyze

      - name: Run tests
        run: |
          # FIXME: UI system screen tests cause segmentation faults in CI but pass locally.
          # Excluding entire directories:
          # - test/src/ui-system/examples/ (all example screen tests)
          # - test/src/ui-system/tools/ (all tool screen tests)
          # - test/src/ui-system/integration/ (all integration tests)
          # These appear to be complex UI tests that may have issues with the CI environment.
          
          # Find all test files except those in problematic directories
          TEST_FILES=$(find test -name "*_test.dart" \
            ! -path "test/src/ui-system/examples/*" \
            ! -path "test/src/ui-system/tools/*" \
            ! -path "test/src/ui-system/integration/*" \
            | tr '\n' ' ')
          
          # Run tests excluding problematic directories
          flutter test --no-pub --coverage $TEST_FILES
        timeout-minutes: 3
