name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_format_analyze_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Check code format
        run: dart format --set-exit-if-changed .

      - name: Run Dart analyzer
        run: flutter analyze

      - name: Run tests
        run: flutter test test/ui_system test/integration test/routing test/screens test/services test/widgets test/src/ui-system.skip/utils test/src/ui-system.skip/accessibility test/src/ui-system.skip/components test/src/ui-system.skip/theme test/src/ui-system.skip/state_widgets test/src/ui-system.skip/integration test/src/ui-system.skip/examples.skip test/src/ui-system.skip/tools.skip test/app_start_test.dart test/widget_test.dart --no-pub --coverage --timeout=30s
        timeout-minutes: 5
