name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_format_analyze_test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Check code format
        run: dart format --set-exit-if-changed .

      - name: Run Dart analyzer
        run: flutter analyze

      - name: Run tests
        run: flutter test --no-pub
        timeout-minutes: 3
